const en = {
  loading: 'Reading this browser…',
  screen: 'Screen and window',
  preferences: 'Preferences',
  browser: 'Browser',
  names: {
    viewport: 'Viewport',
    devicePixels: 'Viewport in device pixels',
    ratio: 'Pixel ratio',
    screen: 'Screen',
    available: 'Screen, without taskbar',
    orientation: 'Orientation',
    depth: 'Colour depth',
    pointer: 'Pointer',
    hover: 'Can hover',
    touch: 'Touch points',
    scheme: 'Colour scheme',
    motion: 'Reduced motion',
    contrast: 'Contrast',
    forced: 'Forced colours',
    languages: 'Languages',
    timeZone: 'Time zone',
    cookies: 'Cookies',
    online: 'Online',
    cores: 'Processor cores',
    memory: 'Memory',
    userAgent: 'User agent'
  },
  px: '{size} px',
  bit: '{bits} bit',
  gb: 'about {gb} GB',
  yes: 'yes',
  no: 'no',
  on: 'on',
  off: 'off',
  pointers: { fine: 'fine (a mouse)', coarse: 'coarse (a finger)', none: 'none' },
  schemes: { dark: 'dark', light: 'light' },
  contrasts: { more: 'more', less: 'less', custom: 'custom', none: 'no preference' },
  hint: 'The values follow the window: resize it, zoom, or change a setting of the system and they change here.',
  key: 'Key events',
  keyPlaceholder: 'Click here and press a key',
  keyHint: 'Shows what a keydown event says. Nothing is typed; Tab moves on as usual.',
  keyNames: {
    key: 'event.key',
    code: 'event.code',
    keyCode: 'event.keyCode',
    location: 'Location',
    modifiers: 'Held with it',
    repeat: 'Repeating',
    check: 'In code'
  },
  locations: { standard: 'standard', left: 'left', right: 'right', numpad: 'numpad' },
  noModifiers: 'nothing',
  report: 'For a bug report'
};

const nl: typeof en = {
  loading: 'Deze browser wordt gelezen…',
  screen: 'Scherm en venster',
  preferences: 'Voorkeuren',
  browser: 'Browser',
  names: {
    viewport: 'Viewport',
    devicePixels: 'Viewport in apparaatpixels',
    ratio: 'Pixelratio',
    screen: 'Scherm',
    available: 'Scherm, zonder taakbalk',
    orientation: 'Oriëntatie',
    depth: 'Kleurdiepte',
    pointer: 'Aanwijzer',
    hover: 'Kan hoveren',
    touch: 'Aanraakpunten',
    scheme: 'Kleurenschema',
    motion: 'Minder beweging',
    contrast: 'Contrast',
    forced: 'Geforceerde kleuren',
    languages: 'Talen',
    timeZone: 'Tijdzone',
    cookies: 'Cookies',
    online: 'Online',
    cores: 'Processorkernen',
    memory: 'Geheugen',
    userAgent: 'User agent'
  },
  px: '{size} px',
  bit: '{bits} bit',
  gb: 'ongeveer {gb} GB',
  yes: 'ja',
  no: 'nee',
  on: 'aan',
  off: 'uit',
  pointers: { fine: 'fijn (een muis)', coarse: 'grof (een vinger)', none: 'geen' },
  schemes: { dark: 'donker', light: 'licht' },
  contrasts: { more: 'meer', less: 'minder', custom: 'aangepast', none: 'geen voorkeur' },
  hint: 'De waarden volgen het venster: maak het groter of kleiner, zoom, of verander een instelling van het systeem en ze veranderen hier mee.',
  key: 'Toetsaanslagen',
  keyPlaceholder: 'Klik hier en druk op een toets',
  keyHint: 'Toont wat een keydown-event zegt. Er wordt niets getypt; Tab gaat gewoon verder.',
  keyNames: {
    key: 'event.key',
    code: 'event.code',
    keyCode: 'event.keyCode',
    location: 'Plaats',
    modifiers: 'Ingedrukt erbij',
    repeat: 'Herhaalt',
    check: 'In code'
  },
  locations: { standard: 'standaard', left: 'links', right: 'rechts', numpad: 'numeriek blok' },
  noModifiers: 'niets',
  report: 'Voor een bugmelding'
};

export default { en, nl };
