const en = {
  deck: 'Deck',
  decks: { fibonacci: 'Fibonacci', modified: 'Fibonacci, rounded', powers: 'Powers of two', shirts: 'T-shirt sizes' },
  mode: 'Use it to',
  modes: { pick: 'pick my card', tally: 'tally a round' },
  cards: 'Cards',
  cardNames: { '?': 'No idea', '☕': 'Time for a break' } as Record<string, string>,
  pickHint: 'Everyone picks on their own screen. The card stays face down until you turn it, so nobody is steered by another.',
  yours: 'Your card',
  none: 'Pick a card.',
  hidden: 'Picked, face down.',
  shown: 'Your card is {card}.',
  reveal: 'Turn it over',
  hide: 'Turn it back',
  again: 'Pick another',
  tallyHint: 'Tap a card for each one that is shown.',
  times: '{card}, shown {times} times',
  undo: 'Take the last one back',
  clear: 'New round',
  round: 'The round',
  noVotes: 'No cards yet.',
  names: { votes: 'Cards', low: 'Lowest', high: 'Highest', average: 'Average' },
  consensus: 'Everyone says {card}: that is the estimate.',
  spread: 'From {low} to {high}: let the lowest and the highest explain, then pick again.',
  one: 'One estimate so far.',
  noEstimates: 'Nobody gave an estimate.'
};

const nl: typeof en = {
  deck: 'Set',
  decks: { fibonacci: 'Fibonacci', modified: 'Fibonacci, afgerond', powers: 'Machten van twee', shirts: 'T-shirtmaten' },
  mode: 'Gebruik het om',
  modes: { pick: 'mijn kaart te kiezen', tally: 'een ronde te turven' },
  cards: 'Kaarten',
  cardNames: { '?': 'Geen idee', '☕': 'Tijd voor pauze' },
  pickHint: 'Iedereen kiest op zijn eigen scherm. De kaart blijft dicht tot je hem omdraait, zodat niemand door een ander gestuurd wordt.',
  yours: 'Jouw kaart',
  none: 'Kies een kaart.',
  hidden: 'Gekozen, nog dicht.',
  shown: 'Jouw kaart is {card}.',
  reveal: 'Draai om',
  hide: 'Draai terug',
  again: 'Kies een andere',
  tallyHint: 'Tik op een kaart voor elke kaart die getoond wordt.',
  times: '{card}, {times} keer getoond',
  undo: 'Neem de laatste terug',
  clear: 'Nieuwe ronde',
  round: 'De ronde',
  noVotes: 'Nog geen kaarten.',
  names: { votes: 'Kaarten', low: 'Laagste', high: 'Hoogste', average: 'Gemiddelde' },
  consensus: 'Iedereen zegt {card}: dat is de schatting.',
  spread: 'Van {low} tot {high}: laat de laagste en de hoogste het uitleggen, en kies daarna opnieuw.',
  one: 'Eén schatting tot nu toe.',
  noEstimates: 'Niemand gaf een schatting.'
};

export default { en, nl };
