const en = {
  input: 'URL',
  read: 'A {scheme} address with {count} query parameters.',
  readOne: 'A {scheme} address with 1 query parameter.',
  assumed: 'There is no scheme in this, so it is read as https://. ',
  relative: 'An address without a host: only the path, the query and the fragment can be read.',
  errors: { empty: 'Paste a URL.', invalid: 'This is not a URL that can be read.' },
  parts: 'Parts',
  names: {
    scheme: 'scheme',
    username: 'user',
    password: 'password',
    host: 'host',
    hostUnicode: 'host, as it reads',
    port: 'port',
    path: 'path',
    query: 'query',
    fragment: 'fragment',
    origin: 'origin'
  },
  defaultPort: '{port} (not written: the default for {scheme})',
  segments: 'Path, piece by piece',
  emptySegment: '(empty)',
  params: 'Query parameters',
  paramsHint: 'Change a name or a value and the URL follows. The other parameters stay as they were written.',
  noParams: 'There are no query parameters.',
  key: 'Name',
  value: 'Value',
  keyOf: 'Name of parameter {n}',
  valueOf: 'Value of parameter {n}',
  remove: 'Remove',
  removeOf: 'Remove parameter {n}',
  add: 'Add a parameter',
  json: 'Parameters as JSON',
  href: 'As a browser sends it'
};

const nl: typeof en = {
  input: 'URL',
  read: 'Een {scheme}-adres met {count} queryparameters.',
  readOne: 'Een {scheme}-adres met 1 queryparameter.',
  assumed: 'Hier staat geen schema in, dus het is gelezen als https://. ',
  relative: 'Een adres zonder host: alleen het pad, de query en het fragment zijn te lezen.',
  errors: { empty: 'Plak een URL.', invalid: 'Dit is geen URL die te lezen is.' },
  parts: 'Onderdelen',
  names: {
    scheme: 'schema',
    username: 'gebruiker',
    password: 'wachtwoord',
    host: 'host',
    hostUnicode: 'host, zoals je hem leest',
    port: 'poort',
    path: 'pad',
    query: 'query',
    fragment: 'fragment',
    origin: 'origin'
  },
  defaultPort: '{port} (niet geschreven: de standaard voor {scheme})',
  segments: 'Pad, stuk voor stuk',
  emptySegment: '(leeg)',
  params: 'Queryparameters',
  paramsHint: 'Verander een naam of een waarde en de URL volgt. De andere parameters blijven zoals ze geschreven waren.',
  noParams: 'Er zijn geen queryparameters.',
  key: 'Naam',
  value: 'Waarde',
  keyOf: 'Naam van parameter {n}',
  valueOf: 'Waarde van parameter {n}',
  remove: 'Verwijderen',
  removeOf: 'Parameter {n} verwijderen',
  add: 'Parameter toevoegen',
  json: 'Parameters als JSON',
  href: 'Zoals een browser het verstuurt'
};

export default { en, nl };
