const en = {
  input: 'HTML of the page',
  inputHint: 'Paste the source of the page; the <head> is enough. This tool does not fetch anything, so an address is not enough.',
  found: '{count} tags that matter when the page is shared.',
  foundOne: '1 tag that matters when the page is shared.',
  none: 'No Open Graph or Twitter tags, no title and no description in this.',
  empty: 'Paste the HTML of a page.',
  picture: 'The picture',
  pictureHint: 'A picture at another address is not loaded here. Pick the file to see it in the cards and to check its size. It stays in your browser.',
  pictureUnreadable: '{name} is not an image this browser can read.',
  pictureSize: '{name}: {width} × {height} px. ',
  verdicts: {
    good: 'Large enough and in the right shape.',
    low: 'The right shape, but smaller than 1200 × 630: it gets blurry on a sharp screen.',
    ratio: 'Not 1.91 to 1 (like 1200 × 630): the sites cut off the sides or the top and bottom.',
    tooSmall: 'Smaller than 200 × 200: most sites do not show it at all.'
  },
  cards: 'How it is shared',
  cardsHint: 'An impression: every site draws a card a little differently, and changes it now and then.',
  facebook: 'Facebook and LinkedIn',
  x: 'X',
  chat: 'Slack and Discord',
  noTitle: 'No title',
  noHost: 'the domain of the page',
  noPicture: 'No picture',
  pictureAt: 'The picture at {url}',
  pictureAlt: 'The picture that was picked',
  checks: 'To check',
  levels: { good: 'ok', tip: 'tip', fix: 'fix' },
  check: {
    titleMissing: 'There is no title: add og:title.',
    titleFallback: 'No og:title: the sites fall back on {source}. Add og:title to say it without the name of the site behind it.',
    titleLong: 'The title is {length} characters; beyond {max} it gets cut off.',
    titleGood: 'og:title, {length} characters.',
    descriptionMissing: 'There is no description: add og:description.',
    descriptionFallback: 'No og:description: the sites fall back on {source}.',
    descriptionLong: 'The description is {length} characters; beyond {max} it gets cut off.',
    descriptionGood: 'og:description, {length} characters.',
    imageMissing: 'There is no picture: add og:image. A card without one gets far less attention.',
    imageRelative: 'og:image is "{value}": that has to be a whole address, starting with https://.',
    imageHttp: 'og:image starts with http://: some sites only load a picture over https://.',
    imageGood: 'og:image is a whole address.',
    altMissing: 'The picture has no description: add og:image:alt for who can not see it.',
    urlMissing: 'No og:url: the address the page was shared with is used, with whatever was added to it.',
    urlRelative: 'og:url is "{value}": that has to be a whole address, starting with https://.',
    urlGood: 'og:url is a whole address.',
    cardMissing: 'No twitter:card: X shows a small card. Add summary_large_image for a large picture.',
    cardUnknown: 'twitter:card is "{value}": X knows summary, summary_large_image, app and player.',
    cardGood: 'twitter:card is {value}.',
    typeMissing: 'No og:type: the page counts as a website. Say article for an article.'
  },
  tags: 'What the page says',
  tag: 'Tag',
  value: 'Value'
};

const nl: typeof en = {
  input: 'HTML van de pagina',
  inputHint: 'Plak de bron van de pagina; de <head> is genoeg. Deze tool haalt niets op, dus een adres is niet genoeg.',
  found: '{count} tags die ertoe doen als de pagina gedeeld wordt.',
  foundOne: '1 tag die ertoe doet als de pagina gedeeld wordt.',
  none: 'Hier staan geen Open Graph- of Twitter-tags in, geen titel en geen beschrijving.',
  empty: 'Plak de HTML van een pagina.',
  picture: 'De afbeelding',
  pictureHint:
    'Een afbeelding op een ander adres wordt hier niet geladen. Kies het bestand om het in de kaarten te zien en de grootte te controleren. Het blijft in je browser.',
  pictureUnreadable: '{name} is geen afbeelding die deze browser kan lezen.',
  pictureSize: '{name}: {width} × {height} px. ',
  verdicts: {
    good: 'Groot genoeg en in de goede vorm.',
    low: 'De goede vorm, maar kleiner dan 1200 × 630: op een scherp scherm wordt het wazig.',
    ratio: 'Niet 1,91 op 1 (zoals 1200 × 630): de sites snijden de zijkanten of de boven- en onderkant eraf.',
    tooSmall: 'Kleiner dan 200 × 200: de meeste sites tonen het helemaal niet.'
  },
  cards: 'Hoe het gedeeld wordt',
  cardsHint: 'Een indruk: elke site tekent een kaart een beetje anders, en verandert dat af en toe.',
  facebook: 'Facebook en LinkedIn',
  x: 'X',
  chat: 'Slack en Discord',
  noTitle: 'Geen titel',
  noHost: 'het domein van de pagina',
  noPicture: 'Geen afbeelding',
  pictureAt: 'De afbeelding op {url}',
  pictureAlt: 'De afbeelding die gekozen is',
  checks: 'Na te lopen',
  levels: { good: 'ok', tip: 'tip', fix: 'fix' },
  check: {
    titleMissing: 'Er is geen titel: voeg og:title toe.',
    titleFallback: 'Geen og:title: de sites vallen terug op {source}. Voeg og:title toe om het te zeggen zonder de naam van de site erachter.',
    titleLong: 'De titel is {length} tekens; na {max} wordt hij afgekapt.',
    titleGood: 'og:title, {length} tekens.',
    descriptionMissing: 'Er is geen beschrijving: voeg og:description toe.',
    descriptionFallback: 'Geen og:description: de sites vallen terug op {source}.',
    descriptionLong: 'De beschrijving is {length} tekens; na {max} wordt hij afgekapt.',
    descriptionGood: 'og:description, {length} tekens.',
    imageMissing: 'Er is geen afbeelding: voeg og:image toe. Een kaart zonder krijgt veel minder aandacht.',
    imageRelative: 'og:image is "{value}": dat moet een heel adres zijn, beginnend met https://.',
    imageHttp: 'og:image begint met http://: sommige sites laden een afbeelding alleen via https://.',
    imageGood: 'og:image is een heel adres.',
    altMissing: 'De afbeelding heeft geen beschrijving: voeg og:image:alt toe voor wie hem niet kan zien.',
    urlMissing: 'Geen og:url: het adres waarmee de pagina gedeeld werd wordt gebruikt, met alles wat eraan toegevoegd was.',
    urlRelative: 'og:url is "{value}": dat moet een heel adres zijn, beginnend met https://.',
    urlGood: 'og:url is een heel adres.',
    cardMissing: 'Geen twitter:card: X toont een kleine kaart. Voeg summary_large_image toe voor een grote afbeelding.',
    cardUnknown: 'twitter:card is "{value}": X kent summary, summary_large_image, app en player.',
    cardGood: 'twitter:card is {value}.',
    typeMissing: 'Geen og:type: de pagina telt als website. Zeg article voor een artikel.'
  },
  tags: 'Wat de pagina zegt',
  tag: 'Tag',
  value: 'Waarde'
};

export default { en, nl };
