const en = {
  text: 'Text colour',
  background: 'Background colour',
  pickText: 'Pick the text colour',
  pickBackground: 'Pick the background colour',
  swap: 'Swap',
  colourHint: 'HEX, rgb(), hsl(), oklch() or a name.',
  invalid: 'This is not a colour that can be read.',
  ratio: 'Contrast',
  ratioLine: '{ratio} to 1',
  checks: 'WCAG 2.2',
  check: {
    aaNormal: 'AA, text',
    aaLarge: 'AA, large text',
    aaaNormal: 'AAA, text',
    aaaLarge: 'AAA, large text',
    ui: 'AA, icons and edges of controls'
  },
  needs: 'needs {min}:1',
  pass: 'passes',
  fail: 'fails',
  largeHint: 'Large text is at least 24 px, or 18.66 px in bold.',
  preview: 'Preview',
  sample: 'The quick brown fox jumps over the lazy dog.',
  sampleLarge: 'Large text, 24 px',
  sampleButton: 'Button',
  target: 'Aim for',
  targets: { aa: 'AA text (4.5:1)', large: 'AA large text and controls (3:1)', aaa: 'AAA text (7:1)' },
  suggest: 'Nearest colours that pass',
  suggestHint: 'Same hue, only lighter or darker, by as little as it takes.',
  newText: 'Text colour',
  newBackground: 'Background colour',
  already: 'Already passes.',
  none: 'No lightness gets there.',
  use: 'Use',
  useLabel: 'Use {colour} as the {which}',
  which: { text: 'text colour', background: 'background colour' }
};

const nl: typeof en = {
  text: 'Tekstkleur',
  background: 'Achtergrondkleur',
  pickText: 'Kies de tekstkleur',
  pickBackground: 'Kies de achtergrondkleur',
  swap: 'Omwisselen',
  colourHint: 'HEX, rgb(), hsl(), oklch() of een naam.',
  invalid: 'Dit is geen kleur die te lezen is.',
  ratio: 'Contrast',
  ratioLine: '{ratio} op 1',
  checks: 'WCAG 2.2',
  check: {
    aaNormal: 'AA, tekst',
    aaLarge: 'AA, grote tekst',
    aaaNormal: 'AAA, tekst',
    aaaLarge: 'AAA, grote tekst',
    ui: 'AA, iconen en randen van bedieningselementen'
  },
  needs: 'vraagt {min}:1',
  pass: 'slaagt',
  fail: 'zakt',
  largeHint: 'Grote tekst is minstens 24 px, of 18,66 px vet.',
  preview: 'Voorbeeld',
  sample: 'Wazig tv-quiz bracht pa’s jeugd op zijn fiets.',
  sampleLarge: 'Grote tekst, 24 px',
  sampleButton: 'Knop',
  target: 'Mik op',
  targets: { aa: 'AA tekst (4,5:1)', large: 'AA grote tekst en bediening (3:1)', aaa: 'AAA tekst (7:1)' },
  suggest: 'Dichtstbijzijnde kleuren die slagen',
  suggestHint: 'Dezelfde tint, alleen lichter of donkerder, zo weinig als nodig.',
  newText: 'Tekstkleur',
  newBackground: 'Achtergrondkleur',
  already: 'Slaagt al.',
  none: 'Geen lichtheid komt daar.',
  use: 'Gebruik',
  useLabel: 'Gebruik {colour} als {which}',
  which: { text: 'tekstkleur', background: 'achtergrondkleur' }
};

export default { en, nl };
