const en = {
  file: 'Image',
  fileHint: 'Read in your browser, never uploaded. PNG, JPEG, WebP, GIF, AVIF or SVG, up to {max}.',
  fileTooLarge: '{name} is {size}; the limit is {max}.',
  unreadable: '{name} is not an image this browser can read.',
  sampleName: 'sample.png',
  source: '{name}: {width} × {height} px, {size}.',
  none: 'Pick an image, or try the sample.',
  make: 'Make',
  makes: { resize: 'another size', favicons: 'a favicon set' },
  width: 'Width (px)',
  height: 'Height (px)',
  lock: 'Keep the proportions',
  sideError: 'Width and height have to be whole numbers from 1 to {max}.',
  format: 'Format',
  formats: { 'image/png': 'PNG', 'image/jpeg': 'JPEG', 'image/webp': 'WebP' },
  quality: 'Quality',
  qualityValue: '{quality}%',
  jpegHint: 'JPEG has no transparency: what is transparent becomes white.',
  result: 'Result',
  resultAlt: 'The image at {width} × {height} px',
  resultStatus: '{name}: {width} × {height} px, {size}, {percent}% of the size of the original file.',
  download: 'Download',
  background: 'Background of the Apple icon',
  backgroundHint: 'iOS shows black where an icon is transparent, so this one gets a background.',
  notSquare: 'The image is not square: it is centred, with room around it.',
  files: 'Files',
  fileSizes: { 'favicon.ico': '16, 32 and 48 px', 'icon.svg': 'the SVG as it is', 'site.webmanifest': 'points at the two icons' },
  px: '{size} px',
  all: 'Download all as .zip',
  zipName: 'favicons.zip',
  preview: 'Preview',
  previewAlt: 'The icon at {size} px',
  head: 'In the <head>',
  place: 'Put the files in the root of the site.'
};

const nl: typeof en = {
  file: 'Afbeelding',
  fileHint: 'In je browser gelezen, nooit geüpload. PNG, JPEG, WebP, GIF, AVIF of SVG, maximaal {max}.',
  fileTooLarge: '{name} is {size}; de limiet is {max}.',
  unreadable: '{name} is geen afbeelding die deze browser kan lezen.',
  sampleName: 'voorbeeld.png',
  source: '{name}: {width} × {height} px, {size}.',
  none: 'Kies een afbeelding, of probeer het voorbeeld.',
  make: 'Maak',
  makes: { resize: 'een ander formaat', favicons: 'een faviconset' },
  width: 'Breedte (px)',
  height: 'Hoogte (px)',
  lock: 'Verhoudingen behouden',
  sideError: 'Breedte en hoogte moeten hele getallen van 1 tot {max} zijn.',
  format: 'Bestandstype',
  formats: { 'image/png': 'PNG', 'image/jpeg': 'JPEG', 'image/webp': 'WebP' },
  quality: 'Kwaliteit',
  qualityValue: '{quality}%',
  jpegHint: 'JPEG kent geen transparantie: wat doorzichtig is wordt wit.',
  result: 'Resultaat',
  resultAlt: 'De afbeelding op {width} × {height} px',
  resultStatus: '{name}: {width} × {height} px, {size}, {percent}% van de grootte van het oorspronkelijke bestand.',
  download: 'Downloaden',
  background: 'Achtergrond van het Apple-icoon',
  backgroundHint: 'iOS toont zwart waar een icoon doorzichtig is, dus dit icoon krijgt een achtergrond.',
  notSquare: 'De afbeelding is niet vierkant: hij staat in het midden, met ruimte eromheen.',
  files: 'Bestanden',
  fileSizes: { 'favicon.ico': '16, 32 en 48 px', 'icon.svg': 'de SVG zoals hij is', 'site.webmanifest': 'wijst naar de twee iconen' },
  px: '{size} px',
  all: 'Alles downloaden als .zip',
  zipName: 'favicons.zip',
  preview: 'Voorbeeld',
  previewAlt: 'Het icoon op {size} px',
  head: 'In de <head>',
  place: 'Zet de bestanden in de root van de site.'
};

export default { en, nl };
