const en = {
  policy: 'Policy',
  policyHint: 'Type a policy, or paste a whole header or <meta> tag.',
  presets: 'Start from',
  preset: { site: 'A site of its own', strict: 'Strict, with a nonce', locked: 'Everything closed' },
  presetHint: {
    site: 'Everything from the site itself, nothing from elsewhere.',
    strict: 'Scripts only with a nonce. Replace CHANGEME by a new random value in every response.',
    locked: 'Nothing is allowed. Add what the page turns out to need.'
  },
  add: 'Add a directive',
  addButton: 'Add',
  remove: 'Remove {directive}',
  removeShort: 'Remove',
  empty: 'Type or paste a policy.',
  summary: { none: 'Nothing to remark on this policy.', one: '1 remark on this policy.', other: '{count} remarks on this policy.' },
  findings: 'Remarks',
  levels: { bad: 'risk', warn: 'warning', info: 'note' },
  explained: 'What it allows',
  noValue: 'No sources: the same as nothing at all.',
  header: 'As a header',
  meta: 'As a tag in the head',
  metaDropped: 'Left out, because a browser ignores it in a tag: {directives}.',
  reportOnly: 'Only report, block nothing',
  finding: {
    noScript: 'Nothing limits scripts: there is no script-src and no default-src. Stopping injected scripts is the main thing a policy is for.',
    unsafeInline: "{directive} allows 'unsafe-inline': any script injected into the page runs. Use a nonce or a hash for the inline scripts you need.",
    unsafeEval: "{directive} allows 'unsafe-eval': text can be run as code with eval().",
    anyScript: '{directive} allows {value}: scripts from any server.',
    dataScript: '{directive} allows data: — a script can be written into the address itself, which is as open as inline.',
    objectSrc: "Plugins are not switched off. Add object-src 'none'.",
    baseUri:
      "base-uri is missing, and it does not fall back on default-src: an injected <base> tag can point every relative address somewhere else. Add base-uri 'self' or 'none'.",
    frameAncestors:
      "frame-ancestors is missing, and it does not fall back on default-src: any site may show this page in a frame. Add frame-ancestors 'none' or 'self'.",
    unquoted: "{directive}: {value} is read as a server named “{value}”. Keywords, nonces and hashes need single quotes: '{value}'.",
    unknownSource: '{directive}: {value} is not a source a browser knows. It is skipped.',
    unknownDirective: '{directive} is not a directive a browser knows. It is skipped.',
    duplicate: '{directive} is there more than once. A browser keeps the first and ignores the rest.',
    deprecated: '{directive} is out of date. Browsers ignore it or will.',
    noneAndMore: "{directive}: 'none' only works alone. Next to other sources it is ignored.",
    insecure: '{directive} allows {value}, which is not encrypted: anyone on the way can change what comes in.',
    reportOnly: 'This is a report-only header: it reports what it would block and blocks nothing.'
  },
  directive: {
    'default-src': 'The fallback for every kind of content that has no directive of its own.',
    'script-src': 'Scripts.',
    'script-src-elem': 'Scripts in <script> tags.',
    'script-src-attr': 'Scripts in attributes like onclick.',
    'style-src': 'Style sheets and inline styles.',
    'style-src-elem': 'Style sheets in <style> and <link> tags.',
    'style-src-attr': 'Styles in style attributes.',
    'img-src': 'Images and icons.',
    'font-src': 'Fonts.',
    'connect-src': 'What scripts may connect to: fetch, XHR, WebSocket, EventSource.',
    'media-src': 'Audio and video.',
    'object-src': 'Plugins: <object> and <embed>.',
    'frame-src': 'Pages shown in a frame on this page.',
    'child-src': 'Frames and workers, when frame-src or worker-src is not given.',
    'worker-src': 'Workers and service workers.',
    'manifest-src': 'The web app manifest.',
    'base-uri': 'What a <base> tag may point to.',
    'form-action': 'Where forms may be sent.',
    'frame-ancestors': 'Which sites may show this page in a frame.',
    sandbox: 'Puts the page in a sandbox, with only these things allowed.',
    'report-to': 'The reporting group that gets a report of what was blocked.',
    'report-uri': 'The address that gets a report of what was blocked. The older way, still the one every browser knows.',
    'require-trusted-types-for': 'Dangerous DOM functions only take values made by a Trusted Types policy.',
    'trusted-types': 'Which Trusted Types policies may be made.',
    'upgrade-insecure-requests': 'Every http: address in the page is fetched over https: instead.',
    'block-all-mixed-content': 'Blocked http: content on an https: page. Browsers do that themselves now.',
    'prefetch-src': 'What may be prefetched. Dropped from the standard.',
    'plugin-types': 'Which kinds of plugins may load. Dropped from the standard.'
  } as Record<string, string>,
  unknownDirective: 'Not a directive a browser knows.',
  source: {
    none: 'nothing at all',
    self: 'this site itself: same scheme, host and port',
    'unsafe-inline': 'code written in the page itself: inline blocks and attributes',
    'unsafe-eval': 'text run as code: eval() and the like',
    'wasm-unsafe-eval': 'compiling WebAssembly',
    'unsafe-hashes': 'event handlers and style attributes whose hash is in the list',
    'strict-dynamic': 'whatever a trusted script loads itself; hosts and schemes in this list are then ignored',
    'report-sample': 'a report holds the first characters of what was blocked',
    'inline-speculation-rules': 'speculation rules written in the page',
    nonce: 'tags that carry this nonce',
    hash: 'code with exactly this {algorithm} hash',
    scheme: 'anything over {scheme}',
    any: 'any server (but not data:, blob: or filesystem:)',
    host: 'this address',
    wildcard: 'this address and every subdomain under it',
    unquoted: 'read as the name of a server: the single quotes are missing',
    unknown: 'not a source a browser knows'
  }
};

const nl: typeof en = {
  policy: 'Policy',
  policyHint: 'Typ een policy, of plak een hele header of <meta>-tag.',
  presets: 'Begin met',
  preset: { site: 'Een eigen site', strict: 'Streng, met een nonce', locked: 'Alles dicht' },
  presetHint: {
    site: 'Alles van de site zelf, niets van elders.',
    strict: 'Scripts alleen met een nonce. Vervang CHANGEME in elke response door een nieuwe willekeurige waarde.',
    locked: 'Niets mag. Voeg toe wat de pagina nodig blijkt te hebben.'
  },
  add: 'Voeg een directive toe',
  addButton: 'Toevoegen',
  remove: 'Verwijder {directive}',
  removeShort: 'Verwijder',
  empty: 'Typ of plak een policy.',
  summary: { none: 'Niets op te merken over deze policy.', one: '1 opmerking over deze policy.', other: '{count} opmerkingen over deze policy.' },
  findings: 'Opmerkingen',
  levels: { bad: 'risico', warn: 'waarschuwing', info: 'notitie' },
  explained: 'Wat hij toestaat',
  noValue: 'Geen bronnen: hetzelfde als helemaal niets.',
  header: 'Als header',
  meta: 'Als tag in de head',
  metaDropped: 'Weggelaten, omdat een browser het in een tag negeert: {directives}.',
  reportOnly: 'Alleen melden, niets blokkeren',
  finding: {
    noScript: 'Niets beperkt scripts: er is geen script-src en geen default-src. Ingevoegde scripts tegenhouden is waar een policy vooral voor is.',
    unsafeInline:
      "{directive} staat 'unsafe-inline' toe: elk script dat in de pagina wordt ingevoegd, draait. Gebruik een nonce of een hash voor de inline scripts die je nodig hebt.",
    unsafeEval: "{directive} staat 'unsafe-eval' toe: tekst kan als code worden uitgevoerd met eval().",
    anyScript: '{directive} staat {value} toe: scripts van elke server.',
    dataScript: '{directive} staat data: toe — een script kan in het adres zelf worden geschreven, en dat is net zo open als inline.',
    objectSrc: "Plug-ins staan niet uit. Voeg object-src 'none' toe.",
    baseUri:
      "base-uri ontbreekt, en die valt niet terug op default-src: een ingevoegde <base>-tag kan elk relatief adres ergens anders heen laten wijzen. Voeg base-uri 'self' of 'none' toe.",
    frameAncestors:
      "frame-ancestors ontbreekt, en die valt niet terug op default-src: elke site mag deze pagina in een frame tonen. Voeg frame-ancestors 'none' of 'self' toe.",
    unquoted:
      "{directive}: {value} wordt gelezen als een server met de naam “{value}”. Trefwoorden, nonces en hashes hebben enkele aanhalingstekens nodig: '{value}'.",
    unknownSource: '{directive}: {value} is geen bron die een browser kent. Hij wordt overgeslagen.',
    unknownDirective: '{directive} is geen directive die een browser kent. Hij wordt overgeslagen.',
    duplicate: '{directive} staat er vaker dan één keer. Een browser houdt de eerste en negeert de rest.',
    deprecated: '{directive} is verouderd. Browsers negeren hem, of gaan dat doen.',
    noneAndMore: "{directive}: 'none' werkt alleen in zijn eentje. Naast andere bronnen wordt het genegeerd.",
    insecure: '{directive} staat {value} toe, en dat is niet versleuteld: iedereen onderweg kan veranderen wat er binnenkomt.',
    reportOnly: 'Dit is een report-only-header: hij meldt wat hij zou blokkeren en blokkeert niets.'
  },
  directive: {
    'default-src': 'De terugval voor elk soort inhoud zonder eigen directive.',
    'script-src': 'Scripts.',
    'script-src-elem': 'Scripts in <script>-tags.',
    'script-src-attr': 'Scripts in attributen zoals onclick.',
    'style-src': 'Stylesheets en inline stijlen.',
    'style-src-elem': 'Stylesheets in <style>- en <link>-tags.',
    'style-src-attr': 'Stijlen in style-attributen.',
    'img-src': 'Afbeeldingen en iconen.',
    'font-src': 'Lettertypen.',
    'connect-src': 'Waar scripts verbinding mee mogen maken: fetch, XHR, WebSocket, EventSource.',
    'media-src': 'Audio en video.',
    'object-src': 'Plug-ins: <object> en <embed>.',
    'frame-src': 'Pagina’s die in een frame op deze pagina staan.',
    'child-src': 'Frames en workers, als frame-src of worker-src er niet is.',
    'worker-src': 'Workers en service workers.',
    'manifest-src': 'Het web-app-manifest.',
    'base-uri': 'Waar een <base>-tag heen mag wijzen.',
    'form-action': 'Waar formulieren heen gestuurd mogen worden.',
    'frame-ancestors': 'Welke sites deze pagina in een frame mogen tonen.',
    sandbox: 'Zet de pagina in een sandbox, waarin alleen dit mag.',
    'report-to': 'De rapportagegroep die een melding krijgt van wat is geblokkeerd.',
    'report-uri': 'Het adres dat een melding krijgt van wat is geblokkeerd. De oudere manier, en nog steeds de manier die elke browser kent.',
    'require-trusted-types-for': 'Gevaarlijke DOM-functies nemen alleen waarden aan die een Trusted Types-policy heeft gemaakt.',
    'trusted-types': 'Welke Trusted Types-policy’s gemaakt mogen worden.',
    'upgrade-insecure-requests': 'Elk http:-adres in de pagina wordt over https: opgehaald.',
    'block-all-mixed-content': 'Blokkeerde http:-inhoud op een https:-pagina. Browsers doen dat nu zelf.',
    'prefetch-src': 'Wat vooraf opgehaald mag worden. Uit de standaard gehaald.',
    'plugin-types': 'Welke soorten plug-ins mogen laden. Uit de standaard gehaald.'
  },
  unknownDirective: 'Geen directive die een browser kent.',
  source: {
    none: 'helemaal niets',
    self: 'deze site zelf: zelfde schema, host en poort',
    'unsafe-inline': 'code die in de pagina zelf staat: inline blokken en attributen',
    'unsafe-eval': 'tekst die als code wordt uitgevoerd: eval() en dergelijke',
    'wasm-unsafe-eval': 'WebAssembly compileren',
    'unsafe-hashes': 'event handlers en style-attributen waarvan de hash in de lijst staat',
    'strict-dynamic': 'wat een vertrouwd script zelf laadt; hosts en schema’s in deze lijst worden dan genegeerd',
    'report-sample': 'een melding bevat de eerste tekens van wat is geblokkeerd',
    'inline-speculation-rules': 'speculation rules die in de pagina staan',
    nonce: 'tags die deze nonce dragen',
    hash: 'code met precies deze {algorithm}-hash',
    scheme: 'alles over {scheme}',
    any: 'elke server (maar niet data:, blob: of filesystem:)',
    host: 'dit adres',
    wildcard: 'dit adres en elk subdomein eronder',
    unquoted: 'gelezen als de naam van een server: de enkele aanhalingstekens ontbreken',
    unknown: 'geen bron die een browser kent'
  }
};

export default { en, nl };
