const en = {
  search: 'Search',
  searchHint: 'A code like 404 or 4xx, a word like redirect, a type like json, or an extension like .png.',
  found: 'Status codes: {statuses}. Media types: {mimes}.',
  statuses: 'Status codes',
  noStatuses: 'No status code matches.',
  classes: {
    1: '1xx: informational',
    2: '2xx: it worked',
    3: '3xx: look somewhere else',
    4: '4xx: the request is the problem',
    5: '5xx: the server is the problem'
  },
  mimes: 'Media types',
  noMimes: 'No media type matches.',
  type: 'Type',
  extension: 'Extension',
  status: {
    100: 'The headers are fine; send the body.',
    101: 'The server switches to the protocol the client asked for, such as WebSocket.',
    102: 'Received and being worked on; there is no answer yet (WebDAV).',
    103: 'Headers sent ahead of the answer, so the browser can start preloading.',
    200: 'It worked. The answer is in the body.',
    201: 'It worked and something new was made; Location says where it is.',
    202: 'Received, but not done yet: the work happens later.',
    203: 'It worked, but a proxy changed the answer on the way.',
    204: 'It worked and there is nothing to send back.',
    205: 'It worked; clear the form the request came from.',
    206: 'Only the part that was asked for with a Range header.',
    207: 'Several results in one answer, each with its own status (WebDAV).',
    208: 'These members were already listed earlier in the answer (WebDAV).',
    226: 'The answer is a change applied to what the client already has.',
    300: 'There is more than one version; the client chooses.',
    301: 'Moved for good. Use the new address from now on; the method may change to GET.',
    302: 'Somewhere else for now. Keep using the old address; the method may change to GET.',
    303: 'The answer is at another address; fetch it with GET.',
    304: 'Nothing changed since the copy the client has: use that.',
    307: 'Somewhere else for now; repeat the request there with the same method.',
    308: 'Moved for good; repeat the request there with the same method.',
    400: 'The request is not understood: wrong syntax or invalid data.',
    401: 'Not signed in, or the credentials are wrong. Sign in and try again.',
    402: 'Reserved for payments; some APIs use it when a paid limit is reached.',
    403: 'It is known who you are, but you may not do this.',
    404: 'There is nothing at this address.',
    405: 'This address exists, but not for this method; Allow says which ones work.',
    406: 'Nothing here matches what the Accept headers ask for.',
    407: 'Sign in at the proxy first.',
    408: 'The server waited too long for the request to arrive.',
    409: 'The request clashes with how things are now, such as an edit of an old version.',
    410: 'It was here and has been removed for good.',
    411: 'A Content-Length header is required.',
    412: 'A condition in the headers (If-Match, If-Unmodified-Since) does not hold.',
    413: 'The body is larger than the server accepts.',
    414: 'The address is longer than the server accepts.',
    415: 'The server does not accept a body of this Content-Type.',
    416: 'The part asked for with Range lies outside the file.',
    417: 'What the Expect header asks can not be met.',
    418: 'A joke from 1998: the teapot refuses to brew coffee.',
    421: 'The request reached a server that can not answer for this host.',
    422: 'Understood, but the data does not pass validation.',
    423: 'The resource is locked (WebDAV).',
    424: 'Failed because an earlier request it depends on failed (WebDAV).',
    425: 'The server will not risk a request that may be replayed.',
    426: 'Switch to another protocol first; Upgrade says which.',
    428: 'The request has to be conditional (If-Match), to prevent lost updates.',
    429: 'Too many requests in a short time; Retry-After says when to try again.',
    431: 'The headers are too large, often because of cookies.',
    451: 'Not available for legal reasons, such as a court order.',
    500: 'Something went wrong on the server; the request is not to blame.',
    501: 'The server does not know this method.',
    502: 'A proxy or gateway got an invalid answer from the server behind it.',
    503: 'The server is overloaded or down for maintenance; try again later.',
    504: 'A proxy or gateway got no answer in time from the server behind it.',
    505: 'The server does not support this version of HTTP.',
    506: 'A configuration error in content negotiation on the server.',
    507: 'The server has no room to store this (WebDAV).',
    508: 'The server ran in circles while handling the request (WebDAV).',
    510: 'The request needs an extension the server does not have.',
    511: 'Sign in to the network first, as on hotel Wi-Fi.'
  } as Record<number, string>
};

const nl: typeof en = {
  search: 'Zoeken',
  searchHint: 'Een code zoals 404 of 4xx, een woord zoals omleiding, een type zoals json, of een extensie zoals .png.',
  found: 'Statuscodes: {statuses}. Mediatypes: {mimes}.',
  statuses: 'Statuscodes',
  noStatuses: 'Geen statuscode gevonden.',
  classes: {
    1: '1xx: ter informatie',
    2: '2xx: het is gelukt',
    3: '3xx: kijk ergens anders',
    4: '4xx: het ligt aan het verzoek',
    5: '5xx: het ligt aan de server'
  },
  mimes: 'Mediatypes',
  noMimes: 'Geen mediatype gevonden.',
  type: 'Type',
  extension: 'Extensie',
  status: {
    100: 'De headers zijn in orde; stuur de body.',
    101: 'De server schakelt over op het protocol waar de client om vroeg, zoals WebSocket.',
    102: 'Ontvangen en in behandeling; er is nog geen antwoord (WebDAV).',
    103: 'Headers die vooruit worden gestuurd, zodat de browser alvast kan laden.',
    200: 'Het is gelukt. Het antwoord staat in de body.',
    201: 'Het is gelukt en er is iets nieuws gemaakt; Location zegt waar het staat.',
    202: 'Ontvangen, maar nog niet klaar: het werk gebeurt later.',
    203: 'Het is gelukt, maar een proxy heeft het antwoord onderweg aangepast.',
    204: 'Het is gelukt en er is niets terug te sturen.',
    205: 'Het is gelukt; maak het formulier leeg waar het verzoek vandaan kwam.',
    206: 'Alleen het deel waar met een Range-header om gevraagd is.',
    207: 'Meerdere resultaten in één antwoord, elk met een eigen status (WebDAV).',
    208: 'Deze onderdelen stonden al eerder in het antwoord (WebDAV).',
    226: 'Het antwoord is een wijziging op wat de client al heeft.',
    300: 'Er is meer dan één versie; de client kiest.',
    301: 'Voorgoed verhuisd. Gebruik voortaan het nieuwe adres; de methode kan GET worden. Een permanente omleiding.',
    302: 'Tijdelijk ergens anders. Blijf het oude adres gebruiken; de methode kan GET worden. Een tijdelijke omleiding.',
    303: 'Het antwoord staat op een ander adres; haal het op met GET.',
    304: 'Niets veranderd sinds de kopie die de client heeft: gebruik die.',
    307: 'Tijdelijk ergens anders; herhaal het verzoek daar met dezelfde methode. Een tijdelijke omleiding.',
    308: 'Voorgoed verhuisd; herhaal het verzoek daar met dezelfde methode. Een permanente omleiding.',
    400: 'Het verzoek wordt niet begrepen: verkeerde syntax of ongeldige gegevens.',
    401: 'Niet ingelogd, of de inloggegevens kloppen niet. Log in en probeer opnieuw.',
    402: 'Gereserveerd voor betalingen; sommige API’s gebruiken het als een betaalde limiet bereikt is.',
    403: 'Bekend wie je bent, maar je mag dit niet.',
    404: 'Op dit adres staat niets.',
    405: 'Dit adres bestaat, maar niet voor deze methode; Allow zegt welke wel werken.',
    406: 'Niets hier past bij waar de Accept-headers om vragen.',
    407: 'Log eerst in bij de proxy.',
    408: 'De server heeft te lang op het verzoek gewacht.',
    409: 'Het verzoek botst met hoe het nu is, zoals een wijziging op een oude versie.',
    410: 'Het stond hier en is voorgoed weggehaald.',
    411: 'Een Content-Length-header is verplicht.',
    412: 'Een voorwaarde in de headers (If-Match, If-Unmodified-Since) gaat niet op.',
    413: 'De body is groter dan de server accepteert.',
    414: 'Het adres is langer dan de server accepteert.',
    415: 'De server accepteert geen body van dit Content-Type.',
    416: 'Het deel waar met Range om gevraagd is ligt buiten het bestand.',
    417: 'Aan wat de Expect-header vraagt kan niet worden voldaan.',
    418: 'Een grap uit 1998: de theepot weigert koffie te zetten.',
    421: 'Het verzoek kwam bij een server die niet voor deze host kan antwoorden.',
    422: 'Begrepen, maar de gegevens komen niet door de validatie.',
    423: 'De resource is vergrendeld (WebDAV).',
    424: 'Mislukt omdat een eerder verzoek waar het van afhangt mislukte (WebDAV).',
    425: 'De server neemt geen risico met een verzoek dat herhaald kan zijn.',
    426: 'Schakel eerst over op een ander protocol; Upgrade zegt welk.',
    428: 'Het verzoek moet voorwaardelijk zijn (If-Match), om verloren wijzigingen te voorkomen.',
    429: 'Te veel verzoeken in korte tijd; Retry-After zegt wanneer het weer kan.',
    431: 'De headers zijn te groot, vaak door cookies.',
    451: 'Niet beschikbaar om juridische redenen, zoals een uitspraak van een rechter.',
    500: 'Er ging iets mis op de server; het ligt niet aan het verzoek.',
    501: 'De server kent deze methode niet.',
    502: 'Een proxy of gateway kreeg een ongeldig antwoord van de server erachter.',
    503: 'De server is overbelast of in onderhoud; probeer het later opnieuw.',
    504: 'Een proxy of gateway kreeg niet op tijd antwoord van de server erachter.',
    505: 'De server ondersteunt deze versie van HTTP niet.',
    506: 'Een configuratiefout in content negotiation op de server.',
    507: 'De server heeft geen ruimte om dit op te slaan (WebDAV).',
    508: 'De server liep in een kringetje bij het afhandelen van het verzoek (WebDAV).',
    510: 'Het verzoek heeft een extensie nodig die de server niet heeft.',
    511: 'Log eerst in op het netwerk, zoals bij wifi in een hotel.'
  }
};

export default { en, nl };
