const en = {
  make: 'Make a',
  makes: { gradient: 'gradient', shadow: 'box shadow' },
  kind: 'Kind',
  kinds: { linear: 'linear', radial: 'radial', conic: 'conic' },
  angle: 'Angle',
  angleValue: '{angle}°',
  shape: 'Shape',
  shapes: { circle: 'circle', ellipse: 'ellipse' },
  oklch: 'Mix the colours in OKLCH',
  oklchHint: 'Smoother, without a grey middle between opposite colours. Browsers since 2023.',
  repeating: 'Repeat',
  stops: 'Colours',
  stop: 'Colour {n}',
  pickStop: 'Pick colour {n}',
  pickColour: 'Pick the colour',
  position: 'Position of colour {n} (%)',
  addStop: 'Add a colour',
  removeStop: 'Remove colour {n}',
  layers: 'Layers',
  layer: 'Layer {n}',
  x: 'Right (px)',
  y: 'Down (px)',
  blur: 'Blur (px)',
  spread: 'Spread (px)',
  colour: 'Colour',
  inset: 'Inside',
  addLayer: 'Add a layer',
  removeLayer: 'Remove layer {n}',
  presets: 'Start from',
  preset: { soft: 'Soft', lifted: 'Lifted', sharp: 'Sharp', inner: 'Inside' },
  remove: 'Remove',
  preview: 'Preview',
  css: 'CSS',
  invalid: 'Colour {n} can not be read.',
  invalidLayer: 'The colour of layer {n} can not be read.',
  card: 'A card'
};

const nl: typeof en = {
  make: 'Maak een',
  makes: { gradient: 'gradient', shadow: 'box-shadow' },
  kind: 'Soort',
  kinds: { linear: 'lineair', radial: 'radiaal', conic: 'conisch' },
  angle: 'Hoek',
  angleValue: '{angle}°',
  shape: 'Vorm',
  shapes: { circle: 'cirkel', ellipse: 'ellips' },
  oklch: 'Meng de kleuren in OKLCH',
  oklchHint: 'Vloeiender, zonder grijs midden tussen tegengestelde kleuren. Browsers sinds 2023.',
  repeating: 'Herhaal',
  stops: 'Kleuren',
  stop: 'Kleur {n}',
  pickStop: 'Kies kleur {n}',
  pickColour: 'Kies de kleur',
  position: 'Positie van kleur {n} (%)',
  addStop: 'Voeg een kleur toe',
  removeStop: 'Verwijder kleur {n}',
  layers: 'Lagen',
  layer: 'Laag {n}',
  x: 'Rechts (px)',
  y: 'Omlaag (px)',
  blur: 'Vervaging (px)',
  spread: 'Spreiding (px)',
  colour: 'Kleur',
  inset: 'Binnenin',
  addLayer: 'Voeg een laag toe',
  removeLayer: 'Verwijder laag {n}',
  presets: 'Begin met',
  preset: { soft: 'Zacht', lifted: 'Opgetild', sharp: 'Scherp', inner: 'Binnenin' },
  remove: 'Verwijder',
  preview: 'Voorbeeld',
  css: 'CSS',
  invalid: 'Kleur {n} is niet te lezen.',
  invalidLayer: 'De kleur van laag {n} is niet te lezen.',
  card: 'Een kaart'
};

export default { en, nl };
